spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      redis:
        uri: "redis://localhost:6379"
        index: "vectorstore"
        prefix: "default:"
        initialize-schema: true
rag:
  etl:
    source-dir: "classpath:weather-data"
